version: '3.8'

# ps: proxy-server
services:
  ps_client:
    image: ps_client
    container_name: ps_client
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - ps_network

  ps_server:
    image: ps_server
    container_name: ps_server
    stdin_open: true
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: unless-stopped
    volumes:
      - '/app/node_modules'
      - './:/app'
    networks:
      - ps_network

  ps_mysql:
    image: ps_mysql
    container_name: ps_mysql
    restart: always
    build:
      context: ./mysql
      args:
        - MYSQL_DATABASE=quizz
        - MYSQL_USER=quizz
        - MYSQL_PASSWORD=quizz
        - MYSQL_ROOT_PASSWORD=quizz
    environment:
      - MYSQL_ROOT_PASSWORD=quizz
    ports:
      - '3306:3306'
    networks:
      - ps_network

networks:
  ps_network:
    driver: bridge
