FROM openresty/openresty:alpine

# nginx configuration
COPY *.conf /usr/local/openresty/nginx/conf

# custom script for handle logic
# COPY *.lua /usr/local/openresty/nginx/

# third party libs or custom libs
# COPY lib/*.lua /usr/local/openresty/lualib/required.lua